name: task_list_app
description: A minimal Flutter app for adding, editing and deleting tasks
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true
